name: fluttercomponentui
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.4
  crypto: ^3.0.6
  custom_refresh_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^6.0.0
  http: ^1.3.0
  http_parser: ^4.1.2
  iconsax_flutter: ^1.0.0
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: ^0.19.0
  localstorage: ^6.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.4
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  awesome_snackbar_content: ^0.1.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/